_BASE_: "Base-SOLOv2.yaml"
MODEL:
  META_ARCHITECTURE: "SOLOv2_contrast"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
INPUT:
  CROP:
    ENABLED: True
  MIN_SIZE_TRAIN: [400,1200]
  MIN_SIZE_TRAIN_SAMPLING: "range"
SOLVER:
  IMS_PER_BATCH: 24
  AMP:
    ENABLED: true
  BASE_LR: 0.01
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 30000
  # CLIP_GRADIENTS:
  #   CLIP_TYPE: value
  #   CLIP_VALUE: 1.0
  #   ENABLED: false
  #   NORM_TYPE: 2.0
  STEPS: (80000, 110000)
  MAX_ITER: 120000