MODEL:
  META_ARCHITECTURE: "CondInst"
  MASK_ON: True
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    THRESH_WITH_CTR: True
    USE_SCALE: True
  CONDINST:
    MASK_OUT_STRIDE: 2
    MAX_PROPOSALS: 500
DATASETS:
  TRAIN: ("coco_2017_val",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (80000, 100000)
  MAX_ITER: 120000
# INPUT:
#   MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800, 1024)
  MAX_SIZE_TRAIN: 2048
  MIN_SIZE_TEST: 1000
  MASK_FORMAT: "bitmask"