_BASE_: "Base-CondInst.yaml"
MODEL:
  META_ARCHITECTURE: "CondInst_old"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "output/condinst_MS_R_101_3x"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_test-dev",)