_BASE_: "Base-CondInst.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "output/condinst_MS_R_50_3x"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)