_BASE_: "Base-CondInst.yaml"
MODEL:
  META_ARCHITECTURE: "CondInst_old"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  CONDINST:
    MAX_PROPOSALS: 500
INPUT:
  CROP:
    ENABLED: True
  MIN_SIZE_TRAIN: [400,1200]
  MIN_SIZE_TRAIN_SAMPLING: "range"
SOLVER:
  IMS_PER_BATCH: 4
OUTPUT_DIR: "output/condinst_MS_R_50_1x"
